# Generated by Django 3.2.7 on 2021-09-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='owner',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='dish',
        ),
    ]
